version: '3.3'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: xkmjr3m3
      POSTGRES_DB: bank
  demo-bank:
    image: demo-bank-0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-bank
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank